### ISSUE TITLE
add CI/CD workflow to check code formatting.

### ISSUE THREAD

**Issue by MannuVilasara** [Bulkmailer/BulkMailer-Backend#10]
Please assign me this under hacktoberfest. @ClawedCatalyst 

Will be adding CI/CD workflow to check formatting of the code.

Here's example:
- not formatted code.
![unsuccess](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/ad00dcb0-72bb-4a25-b191-85e1c7b537d5)
- formatted code
![success](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/c9c63dcb-035f-4dc6-a828-d1916e3867d5)

**Comment by ClawedCatalyst** [comment]
Okay @MannuVilasara you can start working on this
